import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  list: { padding: 14, paddingBottom: 8, gap: 10 },
  emptyLoading: {
    marginTop: 40,
  },
  summaryCard: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
    gap: 16,
  },
  scoreBlock: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    minWidth: 72,
  },
  scoreNum: {
    fontSize: 40,
    fontWeight: '800',
    color: COLORS.text,
    lineHeight: 44,
  },
  scoreCount: { fontSize: 11, color: COLORS.textSub, marginTop: 2 },
  distBlock: { flex: 1, gap: 5, justifyContent: 'center' },
  distRow: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  distStar: {
    fontSize: 12,
    color: COLORS.textSub,
    width: 10,
    textAlign: 'right',
  },
  distBar: {
    flex: 1,
    height: 6,
    backgroundColor: COLORS.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  distFill: { height: '100%', backgroundColor: COLORS.star, borderRadius: 3 },
  distCount: {
    fontSize: 11,
    color: COLORS.textSub,
    width: 16,
    textAlign: 'right',
  },
  starItem: {
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  starHintWrap: {
    position: 'absolute',
    zIndex: 10,
    left: -100,
    right: -100,
    alignItems: 'center',
    alignSelf: 'center',
  },
  mediaScrollContent: {
    gap: 8,
    paddingBottom: 0,
  },
  mediaScrollWrap: {
    marginBottom: 12,
    overflow: 'visible',
  },
  submitBtnLoading: {
    opacity: 0.7,
  },
  formCard: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  formTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 12,
  },
  ratingLabel: { fontSize: 13, color: COLORS.textSub, marginBottom: 8 },
  starPicker: { flexDirection: 'row', gap: 4, marginBottom: 4 },
  starHint: {
    position: 'absolute',
    bottom: 7,
    backgroundColor: 'rgba(0,0,0,0.75)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    zIndex: 10,
  },
  starHintText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '600',
  },
  ratingHint: {
    fontSize: 13,
    color: COLORS.primary,
    fontWeight: '600',
    marginBottom: 12,
    height: 18,
  },
  reviewInput: {
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: COLORS.text,
    minHeight: 100,
    marginBottom: 12,
    backgroundColor: COLORS.bg,
  },
  mediaPreviewWrap: { marginRight: 8, position: 'relative', zIndex: 1 },
  removeMediaBtn: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: COLORS.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMoreMediaBtn: {
    width: 80,
    height: 80,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.bg,
  },
  formActions: { gap: 10 },
  mediaPickerBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    borderStyle: 'dashed',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: COLORS.primaryLight,
  },
  mediaPickerText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.primary,
    fontWeight: '500',
  },
  mediaCount: { fontSize: 12, color: COLORS.textLight },
  submitRow: { flexDirection: 'row', gap: 10 },
  cancelBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.border,
  },
  cancelBtnText: { fontSize: 14, fontWeight: '600', color: COLORS.textSub },
  submitBtn: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    paddingVertical: 13,
    borderRadius: 12,
    elevation: 2,
  },
  submitBtnText: { fontSize: 14, fontWeight: '700', color: COLORS.white },

  filterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.border,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 8,
  },
  iconWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
    textAlignVertical: 'center',
  },
  filterDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.danger,
    marginLeft: 2,
  },
  filterClearChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  filterClearChipText: {
    fontSize: 12,
    color: COLORS.primary,
    fontWeight: '600',
  },
  filterClearIcon: {
    marginTop: 1.5,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  menuContent: {
    borderRadius: 14,
    backgroundColor: COLORS.white,
  },
  menuItemTextDanger: {
    color: COLORS.danger,
  },
  mediaContent: {
    gap: 8,
    marginTop: 10,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 10,
  },
  cardMeta: { flex: 1, gap: 4 },
  userName: { fontSize: 14, fontWeight: '600', color: COLORS.text },
  dateText: { fontSize: 11, color: COLORS.textLight },
  comment: { fontSize: 13, color: COLORS.textSub, lineHeight: 20 },
  mediaThumb: { width: 80, height: 80, borderRadius: 8 },
  videoThumb: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
    gap: 10,
  },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text },
  emptyText: { fontSize: 13, color: COLORS.textSub },
  bsHandle: {
    paddingHorizontal: 16,
    paddingBottom: 9,
  },
  hitSlop: {
    top: 8,
    bottom: 8,
    left: 8,
    right: 10,
  },
  hitSlop2: {
    top: 6,
    bottom: 6,
    left: 6,
    right: 6,
  },
  hitSlop3: {
    top: 8,
    bottom: 8,
    left: 8,
    right: 8,
  },
  bsCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },

  bsHandleBar: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.gray,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 2,
  },
  bsHandleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  bsHandleTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.text,
    flex: 1,
    textAlign: 'left',
  },
  bsContent: { paddingHorizontal: 16, paddingVertical: 12, paddingBottom: 14 },
  bsBackground: {
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
  },
  bsChipIcon: {
    marginRight: 3,
  },
  bsSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.textSub,
    marginBottom: 13,
  },
  bsChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  bsChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  bsChipActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  bsChipText: { fontSize: 13, color: COLORS.textSub, fontWeight: '500' },
  bsChipTextActive: { color: COLORS.primary, fontWeight: '700' },
  bsFooter: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingTop: 10,
    gap: 10,
    backgroundColor: COLORS.white,
  },
  bsClearBtn: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.border,
  },
  bsClearText: { fontSize: 14, fontWeight: '600', color: COLORS.textSub },
  bsApplyBtn: {
    flex: 2,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    elevation: 2,
  },
  bsApplyText: { fontSize: 14, fontWeight: '700', color: COLORS.white },
  errorText: {
    fontSize: 12,
    color: COLORS.danger,
    marginTop: -8,
    marginBottom: 8,
  },
  inputError: {
    borderColor: COLORS.danger,
  },
  videoThumbFallback: {
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  menuItemText: {
    fontSize: 14,
    color: COLORS.text,
  },
});
