import { StyleSheet } from 'react-native';
import { COLORS, GRID_GAP } from '@/constants/constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  list: {},

  profileHeader: {
    alignItems: 'center',
    backgroundColor: COLORS.cardShadow,
    paddingTop: 28,
    paddingBottom: 20,
    paddingHorizontal: 14,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
    borderBottomLeftRadius: 34,
    borderBottomRightRadius: 34,
  },
  profileName: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text,
    marginTop: 12,
  },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    gap: 24,
  },
  statItem: { alignItems: 'center', minWidth: 64 },
  statNum: { fontSize: 18, fontWeight: '800', color: COLORS.primary },
  statLabel: { fontSize: 12, color: COLORS.textSub, marginTop: 2 },
  statDivider: { width: 1, height: 28, backgroundColor: COLORS.border },

  section: { paddingHorizontal: 14, paddingTop: 16, paddingBottom: 6 },
  sectionExtraPadding: {
    paddingTop: 12,
  },
  emptyInlineText: {
    fontSize: 13,
    color: COLORS.textSub,
    marginTop: 4,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 10,
  },
  sectionAction: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.primary,
  },
  gridCell: {
    width: '32.3%',
    aspectRatio: 1,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: COLORS.border,
    marginBottom: GRID_GAP,
  },
  gridImage: { width: '100%', height: '100%' },
  gridVideoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15,23,42,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeInfo: {
    flex: 1,
  },
  mediaContent: {
    gap: 8,
    marginTop: 10,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 14,
    marginBottom: 10,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  placeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingBottom: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  checkinCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 14,
    marginBottom: 10,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  placeIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: COLORS.primaryLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeName: { fontSize: 14, fontWeight: '700', color: COLORS.text },
  placeAddress: { fontSize: 12, color: COLORS.textSub, marginTop: 1 },

  cardTopMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  dateText: { fontSize: 11, color: COLORS.textLight },
  comment: { fontSize: 13, color: COLORS.textSub, lineHeight: 20 },

  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 60,
    gap: 10,
  },
  emptyTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text },
  checkinInfo: {
    flex: 1,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
});
