import { StatusBar, StyleSheet } from 'react-native';
import { ThemeColors } from '@/theme/colors';

export const createMapScreenStyles = (COLORS: ThemeColors) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    map: { flex: 1 },

    topBar: {
      position: 'absolute',
      top: (StatusBar.currentHeight ?? 0) + 16,
      left: 16,
      right: 16,
      zIndex: 20,
    },
    searchRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    searchBox: {
      flex: 1,
      height: 50,
      backgroundColor: COLORS.surface,
      borderRadius: 14,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      elevation: 6,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 8,
      borderWidth: 1.5,
      borderColor: 'transparent',
    },
    searchBoxFocused: { borderColor: COLORS.primary },
    searchInput: { flex: 1, fontSize: 13, color: COLORS.text, height: 50 },
    statsBox: {
      height: 50,
      minWidth: 56,
      backgroundColor: COLORS.primary,
      borderRadius: 14,
      paddingHorizontal: 10,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
    },
    statsValue: {
      fontSize: 18,
      fontWeight: '700',
      color: '#fff',
      lineHeight: 20,
    },
    statsLabel: {
      fontSize: 8,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.7)',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      textAlign: 'center',
      lineHeight: 10,
    },
    routeToggleBtn: {
      width: 50,
      height: 50,
      backgroundColor: COLORS.surface,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 6,
      borderWidth: 1.5,
      borderColor: COLORS.primary,
    },
    suggestionList: {
      marginTop: 6,
      backgroundColor: COLORS.surface,
      borderRadius: 14,
      elevation: 10,
      overflow: 'hidden',
      shadowColor: '#000',
      shadowOpacity: 0.12,
      shadowRadius: 10,
    },
    suggestLoading: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    suggestLoadingText: { fontSize: 12, color: COLORS.textMuted },
    suggestionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 11,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.surfaceMuted,
      gap: 10,
    },
    suggestIcon: {
      width: 30,
      height: 30,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    suggestTextWrap: {
      flex: 1,
    },
    suggestName: { fontSize: 13, fontWeight: '700', color: COLORS.text },
    suggestSub: { fontSize: 11, color: COLORS.textMuted, marginTop: 1 },
    filterBar: {
      position: 'absolute',
      top: (StatusBar.currentHeight ?? 0) + 82,
      left: 0,
      right: 0,
      zIndex: 10,
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 20,
      backgroundColor: COLORS.surface,
      borderWidth: 1.5,
      borderColor: COLORS.border,
      elevation: 3,
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: 4,
    },
    filterText: { fontSize: 12, fontWeight: '600', color: COLORS.textSec },
    routePanel: {
      position: 'absolute',
      top: (StatusBar.currentHeight ?? 0) + 16,
      left: 16,
      right: 16,
      backgroundColor: COLORS.surface,
      borderRadius: 18,
      padding: 14,
      elevation: 12,
      shadowColor: '#000',
      shadowOpacity: 0.15,
      shadowRadius: 12,
      zIndex: 20,
    },
    routePanelHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 12,
    },
    routePanelTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: '700',
      color: COLORS.text,
    },
    routeCloseBtn: {
      width: 32,
      height: 32,
      borderRadius: 8,
      backgroundColor: COLORS.surfaceMuted,
      justifyContent: 'center',
      alignItems: 'center',
    },
    routeInputsWrapper: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    routeIconsCol: {
      width: 22,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 4,
    },
    routeDotsMiddle: {
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: 24,
      gap: 0.5,
      marginVertical: 5,
    },
    routeDotSmall: {
      width: 2,
      height: 2,
      borderRadius: 2,
      backgroundColor: COLORS.textMuted,
    },
    routeInputsCol: { flex: 1, gap: 8 },
    routeInputWrap: {
      height: 42,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.background,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: COLORS.border,
      paddingLeft: 12,
      paddingRight: 6,
    },
    routeInputWrapActive: {
      borderColor: COLORS.primary,
      backgroundColor: COLORS.primaryLight,
    },
    routeInput: { flex: 1, fontSize: 13, color: COLORS.text, height: 42 },
    routeInputMyLoc: { color: COLORS.primary, fontWeight: '600' },
    routeInputClear: { padding: 4 },
    swapBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
    },
    routeLoadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 8,
      paddingHorizontal: 4,
    },
    routeLoadingText: { fontSize: 12, color: COLORS.primary },
    routeDropdown: {
      marginTop: 8,
      backgroundColor: COLORS.background,
      borderRadius: 10,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    suggestLoadingIndicator: {
      margin: 8,
    },
    dropdownTextWrap: {
      flex: 1,
    },
    dropdownItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 11,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
      gap: 10,
    },
    dropdownIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: COLORS.iconBgSubtle,
      justifyContent: 'center',
      alignItems: 'center',
    },
    myLocRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
      gap: 10,
    },
    myLocIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: COLORS.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
    },
    myLocText: { fontSize: 13, fontWeight: '700', color: COLORS.primary },
    recentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 4,
    },
    recentHeaderText: {
      fontSize: 11,
      fontWeight: '600',
      color: COLORS.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    loadingBadge: {
      position: 'absolute',
      top: (StatusBar.currentHeight ?? 0) + 130,
      alignSelf: 'center',
      backgroundColor: COLORS.surface,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      elevation: 8,
    },
    loadingText: { fontSize: 13, color: COLORS.primary, fontWeight: '600' },
    hintBadge: {
      position: 'absolute',
      top: (StatusBar.currentHeight ?? 0) + 130,
      alignSelf: 'center',
      backgroundColor: COLORS.surface,
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      elevation: 6,
    },
    hintText: { fontSize: 12, color: '#92400E' },
    rightActions: {
      position: 'absolute',
      right: 16,
      top: (StatusBar.currentHeight ?? 0) + 130,
      gap: 8,
      zIndex: 10,
    },
    actionBtn: {
      width: 48,
      height: 48,
      backgroundColor: COLORS.surface,
      borderRadius: 14,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 5,
    },
    actionDisabled: {
      opacity: 0.4,
    },
    actionActive: { backgroundColor: COLORS.primary },
    dividerHorizontal: { alignItems: 'center', paddingVertical: 2 },
    dividerLine: { width: 32, height: 1, backgroundColor: COLORS.border },
    markerPopup: {
      position: 'absolute',
      bottom: 110,
      left: 16,
      right: 16,
      backgroundColor: COLORS.surface,
      borderRadius: 20,
      padding: 16,
      elevation: 16,
      shadowColor: COLORS.primary,
      shadowOpacity: 0.2,
      shadowRadius: 16,
      zIndex: 30,
      borderTopWidth: 3,
      borderTopColor: COLORS.primary,
    },
    popupRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 12,
    },
    popupIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    popupName: { fontSize: 15, fontWeight: '700', color: COLORS.text },
    popupAmenity: {
      fontSize: 12,
      color: COLORS.textSec,
      marginTop: 2,
      textTransform: 'capitalize',
    },
    popupClose: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: COLORS.surfaceMuted,
      justifyContent: 'center',
      alignItems: 'center',
    },
    popupActions: { flexDirection: 'row', gap: 10 },
    popupDetailBtn: {
      flex: 1,
      height: 40,
      backgroundColor: COLORS.primary,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    popupDetailText: { color: '#fff', fontWeight: '700', fontSize: 13 },
    popupRouteBtn: {
      flex: 1,
      height: 40,
      backgroundColor: COLORS.primaryLight,
      borderRadius: 10,
      borderWidth: 1.5,
      borderColor: COLORS.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    popupRouteBtnText: {
      color: COLORS.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    bottomSheet: {
      position: 'absolute',
      bottom: 100,
      left: 0,
      right: 0,
      height: 250,
      marginHorizontal: 12,
      marginBottom: 10,
      backgroundColor: COLORS.surface,
      borderRadius: 24,
      overflow: 'hidden',
      elevation: 12,
      shadowColor: '#000',
      shadowOpacity: 0.15,
      shadowRadius: 12,
    },
    sheetHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.surfaceMuted,
    },
    sheetTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text },
    liveChip: {
      backgroundColor: COLORS.primaryLight,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    liveText: {
      fontSize: 9,
      fontWeight: '700',
      color: COLORS.primary,
      textTransform: 'uppercase',
      lineHeight: 13,
      letterSpacing: 0.3,
      textAlign: 'center',
    },
    emptyState: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      gap: 8,
      paddingBottom: 20,
    },
    emptyText: {
      fontSize: 13,
      color: COLORS.textMuted,
      textAlign: 'center',
      paddingHorizontal: 24,
    },
    filterScrollContent: {
      gap: 8,
      paddingHorizontal: 16,
    },
    popupInfo: {
      flex: 1,
    },
    sheetHeaderTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
  });
