import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '@/constants/constants';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight ?? 24 : 48,
    paddingBottom: 12,
    paddingHorizontal: 8,
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  headerBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '600',
    color: COLORS.white,
    textAlign: 'center',
    marginHorizontal: 4,
  },

  scroll: { flex: 1 },
  scrollContent: {},

  heroContainer: { width: '100%', height: 220, position: 'relative' },
  heroImage: { width: '100%', height: '100%' },
  heroTag: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  heroTagText: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.white,
    textTransform: 'capitalize',
  },

  infoCard: {
    backgroundColor: COLORS.white,
    marginHorizontal: 14,
    marginTop: -20,
    borderRadius: 16,
    padding: 16,
    elevation: 3,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 8,
    gap: 10,
  },
  infoCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  placeName: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.text,
  },
  placeNameFlex: {
    flex: 1,
    marginRight: 12,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  ratingValue: { fontSize: 14, fontWeight: '700', color: COLORS.star },
  ratingCount: { fontSize: 12, color: COLORS.textSub },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  addressText: { flex: 1, fontSize: 13, color: COLORS.textSub, lineHeight: 18 },
  tagList: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  tagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  tagChipText: { fontSize: 11, color: COLORS.primary, fontWeight: '500' },

  actionRow: {
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 14,
    marginTop: 12,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: 12,
  },
  actionBtnPrimary: {
    backgroundColor: COLORS.primary,
    elevation: 2,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  actionBtnPrimaryText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.white,
  },
  actionBtnOutline: {
    backgroundColor: COLORS.white,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
  },
  actionBtnOutlineText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.primary,
  },
  actionBtnDisabled: { opacity: 0.5 },
  actionBtnIcon: {
    flex: 0,
    width: 46,
    paddingHorizontal: 0,
  },

  loginBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginHorizontal: 14,
    marginTop: 8,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  loginBannerText: { fontSize: 12, color: COLORS.primary },

  section: { marginTop: 20, marginHorizontal: 14 },
  mediaGalleryContent: {
    gap: 8,
  },
  hitSlop: {
    top: 6,
    bottom: 6,
    left: 6,
    right: 6,
  },
  hitSlop2: {
    top: 8,
    bottom: 8,
    left: 8,
    right: 8,
  },
  checkinLoading: {
    marginVertical: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text },
  sectionCount: { fontWeight: '400', color: COLORS.textSub },
  seeAll: { fontSize: 13, color: COLORS.primary, fontWeight: '600' },

  mediaList: { gap: 8 },
  mediaItem: { position: 'relative', borderRadius: 10, overflow: 'hidden' },
  mediaThumb: { width: 110, height: 80, borderRadius: 10 },
  videoPlayOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },

  reviewCard: {
    backgroundColor: COLORS.white,
    borderRadius: 14,
    padding: 14,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  reviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  reviewMeta: { flex: 1, gap: 3 },
  reviewAuthor: { fontSize: 14, fontWeight: '600', color: COLORS.text },
  reviewDate: { fontSize: 11, color: COLORS.textLight },
  reviewComment: { fontSize: 13, color: COLORS.textSub, lineHeight: 19 },
  reviewMedia: { width: 72, height: 72, borderRadius: 8, marginRight: 6 },
  reviewCountText: {
    fontSize: 12,
    color: COLORS.textSub,
  },

  checkinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    elevation: 1,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  checkinInfo: { flex: 1 },
  checkinName: { fontSize: 13, fontWeight: '600', color: COLORS.text },
  checkinMeta: { fontSize: 11, color: COLORS.textLight, marginTop: 2 },
  checkinBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E8FFF6',
    alignItems: 'center',
    justifyContent: 'center',
  },

  emptyState: { alignItems: 'center', paddingVertical: 28, gap: 6 },
  reviewList: {
    gap: 10,
  },
  reviewLoading: {
    marginVertical: 24,
  },
  reviewRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  reviewMediaContent: {
    gap: 8,
    marginTop: 8,
  },
  emptyText: { fontSize: 13, color: COLORS.textLight },
  emptyHint: { fontSize: 12, color: COLORS.primary },

  avatarBase: {
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    gap: 2,
  },
});
